### ISSUE TITLE
Tout les homebrews ne sont pas tout ajouté au fichier " pack.zip "

### ISSUE THREAD

**Issue by THZoria** [Lunyyx/AtmosphereVanillaFetcher-cli#1]
Seul 5 homebrews sont archivé dans le fichier " pack.zip " final.
> - AwooInstaller
> - Tinfoil
> - TinWoo
> - Daybreak
> - reboot to payload

Pourtant dans le dossier SD les homebrews sont bien télécharger et présent

![unknown](https://user-images.githubusercontent.com/50277488/118389356-e6619000-b629-11eb-9628-098534334d95.png)

**Comment by Lunyyx** [comment]
J'essayerais de regarder pour régler le problème dès que j'ai un peu de temps.
@MurasakiNX sinon si tu as 2 minutes pour jeter un oeil ?

**Comment by THZoria** [comment]
Bug fix avec le commit de @MurasakiNX **[e3cbaef](https://github.com/Lunyyx/AtmosphereVanillaFetcher/commit/e3cbaef3905d44f4075ed986f6b1d06bb5c9383e)**
