### ISSUE TITLE
[Copie et création du pack.zip] Une erreur est survenue

### ISSUE THREAD

**Issue by ghost** [Lunyyx/AtmosphereVanillaFetcher-cli#2]
Bonjour, avant out, merci pour ce nouveau programme.

Pour le problème, je disposes de Node.JS 14.15.4, python 3.9, mais j'obtiens le message suivant à la fin : 

[Copie et création du pack.zip] Une erreur est survenue: Error: ENOENT: no such file or directory, lstat 'D:\Téléchargement\Compressed\AtmosphereVanillaFetcher\temp\atmosphere'

![0](https://user-images.githubusercontent.com/60217162/121408530-cc814780-c960-11eb-8ceb-2bca52ea92f0.png)

Comment résoudre le problème?

Merci d'avance.

**Comment by ghost** [comment]
Bon, j'ai créé le dossier "atmosphere" dans le dossier temp et c'est passé, mais j'imagine que normalement, cela doit ce faire automatiquement.

**Comment by THZoria** [comment]
> Bon, j'ai créé le dossier "atmosphere" dans le dossier temp et c'est passé, mais j'imagine que normalement, cela doit ce faire automatiquement.

Oui c'est censé ce faire automatiquement, on nous a également reporté le souci sur discord on est sur le coup

**Comment by ghost** [comment]
Oki 👍

**Comment by Lunyyx** [comment]
Je tente de prendre en charge le problème étant donné que le problème survient aussi de mon côté, je reviendrais ici dès qu'une solution est trouvée

**Comment by Lunyyx** [comment]
Ok j'ai trouvé le problème, le fichier ``atmosphere.zip`` ne se télécharge pas, je suis en train de chercher une solution

**Comment by Lunyyx** [comment]
Problème normalement résolu, je fais des tests de mes modifs et je publie la MAJ si tout est bon

**Comment by Lunyyx** [comment]
Problème réglé, la cause était le REGEX de Atmosphere qui causait des soucis
