### ISSUE TITLE
[SUGGESTION] Interface GUI

### ISSUE THREAD

**Issue by PoloNX** [Lunyyx/AtmosphereVanillaFetcher-cli#3]
Bonjour à tous, si vous voulez je peux vous faire une interface gui en C++ à l'aide de SDL2.

**Comment by MurasakiNX** [comment]
Bonsoir Polo,

Ta suggestion est très intéressante mais comment comptes-tu traduire le code JavaScript et Python en C++ ? Si tu as déjà des petits tests fais-nous en part sur Discord. 

Mura.

**Comment by PoloNX** [comment]
> Bonsoir Polo,
> 
> Ta suggestion est très intéressante mais comment comptes-tu traduire le code JavaScript et Python en C++ ? Si tu as déjà des petits tests fais-nous en part sur Discord. 
> 
> Mura.

Je vais faire des tests de mon coter et voir si ça marche.

**Comment by Lunyyx** [comment]
Bonjour, peut-être qu'utiliser électron pourrait être une solution... À voir

**Comment by MurasakiNX** [comment]
> Bonjour, peut-être qu'utiliser électron pourrait être une solution... À voir

En effet, l'utilisation d'électron peut être une bonne solution car il n'y aura pas besoin de traduire le code.

**Comment by THZoria** [comment]
Aucun progrès significatif pour le moment, cette question sera rouverte si le projet reprend.
