### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by gh0sti** [Lunyyx/AtmosphereVanillaFetcher-cli#9]
Bonjour, désolé pour ma traduction française j'essaie de suivre le guide en français et j'ai pu faire tourner le script sur ma machine windows, cependant j'obtiens une erreur de type après avoir exécuté node index TypeError: Cannot read properties of undefined (lecture ' URL')
J'ai tout copié exactement de github à exécuter. J'utilise les derniers python et nodejs 20
<img width="1168" alt="image" src="https://github.com/Lunyyx/AtmosphereVanillaFetcher-cli/assets/4202657/5aba7c46-0119-4d5d-ad46-f90a01355eea">

**Comment by THZoria** [comment]
Error fix

**Comment by gh0sti** [comment]
thank you for the quick fix
